### PR TITLE
Fix issue 50

### LINKED ISSUE #50: check of .Rproj for linters yields false positive
I have the following .Rproj file:

```
Version: 1.0

RestoreWorkspace: Default
SaveWorkspace: Default
AlwaysSaveHistory: Default

EnableCodeIndexing: Yes
UseSpacesForTab: Yes
NumSpacesForTab: 2
Encoding: UTF-8

RnwWeave: knitr
LaTeX: XeLaTeX

AutoAppendNewline: Yes

```

which is flagged by `checklist::check_source()`:

image

so probably something needs to be changed so that the .Rproj file is excluded from the lintr check.

### PR DESCRIPTION
**Pull request by hansvancalster**
I think this should fix #50, but I am running into `checklist::check_package()` troubles. 

One question: is `lint_dir()` smart enough to only look inside R chunks in case of Rmd files? The documentation of `lint_dir()` only talks about R files.

### CODE REVIEW

File: R/check_lintr.R [hunk 1]
```diff
@@ -24,7 +24,7 @@ check_lintr <- function(x = ".", quiet = FALSE) {
   if (x$package) {
     linter <- lint_package(path = x$get_path)
   } else {
-    linter <- lint_dir(x$get_path, pattern = "\\.R(md|nw)?")
+    linter <- lint_dir(x$get_path, pattern = "\\.([rR]$|[Rr]md$|[Rr]nw$)")
```
Comment (ThierryO) [inline R/check_lintr.R:27]: This should be sufficient. The R file must have an uppercase R, otherwise the fail `check_filename()`.

```suggestion
    linter <- lint_dir(x$get_path, pattern = "\\.R(md|nw)?$")
```

**Review by ThierryO — CHANGES_REQUESTED** [review]
Good catch. I think we can simplify the regexp

**Review by ThierryO — APPROVED** [review]
